server:
  port: 8070
spring:
  application:
    name: remoteconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/remilelei/EurekaTest.git
          searchPaths: config
          username: remilelei
          password: remilelei
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
